apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: classify
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: REPLACE_WITH_ECR_REGISTRY/classify-api-gateway:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: classify-config
              key: AUTH_SERVICE_URL
        - name: PHOTOS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: classify-config
              key: PHOTOS_SERVICE_URL
        - name: BLUR_DETECTION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: classify-config
              key: BLUR_DETECTION_SERVICE_URL
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: classify-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: classify-config
              key: REDIS_PORT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: classify-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: classify
  labels:
    app: api-gateway
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: api-gateway
