apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: classify
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: REPLACE_WITH_ECR_REGISTRY/classify-auth-service:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: classify-secrets
              key: AUTH_DB_URL
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: classify-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: classify-config
              key: REDIS_PORT
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: classify-secrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: classify-secrets
              key: GOOGLE_CLIENT_SECRET
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: classify-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: classify
  labels:
    app: auth-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: auth-service
