apiVersion: apps/v1
kind: Deployment
metadata:
  name: blur-detection-service
  namespace: classify
  labels:
    app: blur-detection-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blur-detection-service
  template:
    metadata:
      labels:
        app: blur-detection-service
    spec:
      containers:
      - name: blur-detection-service
        image: REPLACE_WITH_ECR_REGISTRY/classify-blur-detection-service:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: classify-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: classify-config
              key: REDIS_PORT
        - name: PHOTOS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: classify-config
              key: PHOTOS_SERVICE_URL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: classify-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: blur-detection-service
  namespace: classify
  labels:
    app: blur-detection-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: blur-detection-service
